# Loan Data Cleaning Using Pandas

This notebook cleans the `bank_loan.csv` dataset using Pandas.

The cleaning process includes:
- Inspecting the dataset
- Checking for missing values
- Checking for duplicate rows
- Identifying and correcting inconsistent values
- Verifying the cleaned dataset
- Saving the cleaned dataset as a new CSV file

#**Import Panda**

*Imported Pandas using import pandas as pd*

In [11]:
import pandas as pd

# **Read the Data**
We read the data/csv using pd.read_csv("")
we uploaded the data into Google Colab on the left sidebar,files,upload

In [12]:
bank_loan = pd.read_csv("/bank_loan.csv")

In [13]:
#import os
#print(os.listdir("/content"))

['.config', 'sample_data']

## Inspect the Dataset

I used `head()` to view the first few rows of the dataset and `info()` to understand the number of rows, columns, data types, and whether there were missing values.

In [25]:
bank_loan.head()

,ID,Age,Experience,Income,ZIP Code,Family,CCAvg,Education,Mortgage,Personal Loan,Securities Account,CD Account,Online,CreditCard
0,1,25,1,49,91108,4,1/60,1,0,0,1,0,0,0
1,2,45,19,34,90089,3,1/50,1,0,0,1,0,0,0
2,3,39,15,11,94720,1,1/00,1,0,0,0,0,0,0
3,4,35,9,100,94112,1,2/70,2,0,0,0,0,0,0
4,5,35,8,45,91330,4,1/00,2,0,0,0,0,0,1

In [18]:
bank_loan.tail()

,ID,Age,Experience,Income,ZIP Code,Family,CCAvg,Education,Mortgage,Personal Loan,Securities Account,CD Account,Online,CreditCard
4995,4996,29,3,40,92697,1,1/90,3,0,0,0,0,1,0
4996,4997,30,4,15,92037,4,0/40,1,85,0,0,0,1,0
4997,4998,63,39,24,93023,2,0/30,3,0,0,0,0,0,0
4998,4999,65,40,49,90034,3,0/50,2,0,0,0,0,1,0
4999,5000,28,4,83,92612,3,0/80,1,0,0,0,0,1,1

In [15]:
bank_loan.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 14 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   ID                  5000 non-null   int64
 1   Age                 5000 non-null   int64
 2   Experience          5000 non-null   int64
 3   Income              5000 non-null   int64
 4   ZIP Code            5000 non-null   int64
 5   Family              5000 non-null   int64
 6   CCAvg               5000 non-null   object
 7   Education           5000 non-null   int64
 8   Mortgage            5000 non-null   int64
 9   Personal Loan       5000 non-null   int64
 10  Securities Account  5000 non-null   int64
 11  CD Account          5000 non-null   int64
 12  Online              5000 non-null   int64
 13  CreditCard          5000 non-null   int64
dtypes: int64(13), object(1)
memory usage: 547.0+ KB

### Missing Values
I checked the dataset for missing values using `isnull().sum()`.
All columns contained 0 missing values, so no missing-value treatment was necessary.

In [17]:
# bank_loan.isnull().sum()
bank_loan.isna().sum()

ID                    0
Age                   0
Experience            0
Income                0
ZIP Code              0
Family                0
CCAvg                 0
Education             0
Mortgage              0
Personal Loan         0
Securities Account    0
CD Account            0
Online                0
CreditCard            0
dtype: int64

### Duplicate Rows
I checked the dataset for duplicate rows using `duplicated().sum()`.
The result was 0, meaning there were no duplicate rows to remove.

In [20]:
bank_loan.duplicated().sum()

np.int64(0)

## Check for Inconsistent Categorical Values

I checked the unique values in the categorical and binary columns to identify unexpected or invalid values.

In [21]:
bank_loan.nunique()

ID                    5000
Age                     45
Experience              47
Income                 162
ZIP Code               468
Family                   4
CCAvg                  108
Education                3
Mortgage               347
Personal Loan            2
Securities Account       2
CD Account               2
Online                   2
CreditCard               2
dtype: int64

### Inconsistent Values
I found negative values in the Experience column. Negative years of work experience are not logically valid, so I replaced all negative Experience values with 0. This avoids keeping impossible values while not assuming an exact number of years of experience.

In [22]:
print("Education:", bank_loan["Education"].unique())
print("Personal Loan:", bank_loan["Personal Loan"].unique())
print("Securities Account:", bank_loan["Securities Account"].unique())
print("CD Account:", bank_loan["CD Account"].unique())
print("Online:", bank_loan["Online"].unique())
print("CreditCard:", bank_loan["CreditCard"].unique())

Education: [1 2 3]
Personal Loan: [0 1]
Securities Account: [1 0]
CD Account: [0 1]
Online: [0 1]
CreditCard: [0 1]

In [23]:
bank_loan.describe()

,ID,Age,Experience,Income,ZIP Code,Family,Education,Mortgage,Personal Loan,Securities Account,CD Account,Online,CreditCard
count,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.00000,5000.000000,5000.000000
mean,2500.500000,45.338400,20.104600,73.774200,93152.503200,2.396400,1.881000,56.498800,0.096000,0.104400,0.06040,0.596800,0.294000
std,1443.520003,11.463166,11.467954,46.033729,2121.852005,1.147663,0.839869,101.713802,0.294621,0.305809,0.23825,0.490589,0.455637
min,1.000000,23.000000,-3.000000,8.000000,9307.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000
25%,1250.750000,35.000000,10.000000,39.000000,91911.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000
50%,2500.500000,45.000000,20.000000,64.000000,93437.000000,2.000000,2.000000,0.000000,0.000000,0.000000,0.00000,1.000000,0.000000
75%,3750.250000,55.000000,30.000000,98.000000,94608.000000,3.000000,3.000000,101.000000,0.000000,0.000000,0.00000,1.000000,1.000000
max,5000.000000,67.000000,43.000000,224.000000,96651.000000,4.000000,3.000000,635.000000,1.000000,1.000000,1.00000,1.000000,1.000000

## Identify Invalid Experience Values

I filtered the `Experience` column to find records containing negative values.

In [24]:
bank_loan[bank_loan["Experience"] < 0]

,ID,Age,Experience,Income,ZIP Code,Family,CCAvg,Education,Mortgage,Personal Loan,Securities Account,CD Account,Online,CreditCard
89,90,25,-1,113,94303,4,2/30,3,0,0,0,0,0,1
226,227,24,-1,39,94085,2,1/70,2,0,0,0,0,0,0
315,316,24,-2,51,90630,3,0/30,3,0,0,0,0,1,0
451,452,28,-2,48,94132,2,1/75,3,89,0,0,0,1,0
524,525,24,-1,75,93014,4,0/20,1,0,0,0,0,1,0
536,537,25,-1,43,92173,3,2/40,2,176,0,0,0,1,0
540,541,25,-1,109,94010,4,2/30,3,314,0,0,0,1,0
576,577,25,-1,48,92870,3,0/30,3,0,0,0,0,0,1
583,584,24,-1,38,95045,2,1/70,2,0,0,0,0,1,0
597,598,24,-2,125,92835,2,7/20,1,0,0,1,0,0,1
649,650,25,-1,82,92677,4,2/10,3,0,0,0,0,1,0
670,671,23,-1,61,92374,4,2/60,1,239,0,0,0,1,0
686,687,24,-1,38,92612,4,0/60,2,0,0,0,0,1,0
793,794,24,-2,150,94720,2,2/00,1,0,0,0,0,1,0
889,890,24,-2,82,91103,2,1/60,3,0,0,0,0,1,1
909,910,23,-1,149,91709,1,6/33,1,305,0,0,0,0,1
1173,1174,24,-1,35,94305,2,1/70,2,0,0,0,0,0,0
1428,1429,25,-1,21,94583,4,0/40,1,90,0,0,0,1,0
1522,1523,25,-1,101,94720,4,2/30,3,256,0,0,0,0,1
1905,1906,25,-1,112,92507,2,2/00,1,241,0,0,0,1,0
2102,2103,25,-1,81,92647,2,1/60,3,0,0,0,0,1,1
2430,2431,23,-1,73,92120,4,2/60,1,0,0,0,0,1,0
2466,2467,24,-2,80,94105,2,1/60,3,0,0,0,0,1,0
2545,2546,25,-1,39,94720,3,2/40,2,0,0,0,0,1,0
2618,2619,23,-3,55,92704,3,2/40,2,145,0,0,0,1,0
2717,2718,23,-2,45,95422,4,0/60,2,0,0,0,0,1,1
2848,2849,24,-1,78,94720,2,1/80,2,0,0,0,0,0,0
2876,2877,24,-2,80,91107,2,1/60,3,238,0,0,0,0,0
2962,2963,23,-2,81,91711,2,1/80,2,0,0,0,0,0,0
2980,2981,25,-1,53,94305,3,2/40,2,0,0,0,0,0,0
3076,3077,29,-1,62,92672,2,1/75,3,0,0,0,0,0,1
3130,3131,23,-2,82,92152,2,1/80,2,0,0,1,0,0,1
3157,3158,23,-1,13,94720,4,1/00,1,84,0,0,0,1,0
3279,3280,26,-1,44,94901,1,2/00,2,0,0,0,0,0,0
3284,3285,25,-1,101,95819,4,2/10,3,0,0,0,0,0,1
3292,3293,25,-1,13,95616,4,0/40,1,0,0,1,0,0,0
3394,3395,25,-1,113,90089,4,2/10,3,0,0,0,0,1,0
3425,3426,23,-1,12,91605,4,1/00,1,90,0,0,0,1,0
3626,3627,24,-3,28,90089,4,1/00,3,0,0,0,0,0,0
3796,3797,24,-2,50,94920,3,2/40,2,0,0,1,0,0,0
3824,3825,23,-1,12,95064,4,1/00,1,0,0,1,0,0,1
3887,3888,24,-2,118,92634,2,7/20,1,0,0,1,0,1,0
3946,3947,25,-1,40,93117,3,2/40,2,0,0,0,0,1,0
4015,4016,25,-1,139,93106,2,2/00,1,0,0,0,0,0,1
4088,4089,29,-1,71,94801,2,1/75,3,0,0,0,0,0,0
4116,4117,24,-2,135,90065,2,7/20,1,0,0,0,0,1,0
4285,4286,23,-3,149,93555,2,7/20,1,0,0,0,0,1,0
4411,4412,23,-2,75,90291,2,1/80,2,0,0,0,0,1,1
4481,4482,25,-2,35,95045,4,1/00,3,0,0,0,0,1,0
4514,4515,24,-3,41,91768,4,1/00,3,0,0,0,0,1,0
4582,4583,25,-1,69,92691,3,0/30,3,0,0,0,0,1,0
4957,4958,29,-1,50,95842,2,1/75,3,0,0,0,0,0,1

## Correct Invalid Experience Values

I replaced all negative `Experience` values with 0.

In [26]:
bank_loan.loc[bank_loan["Experience"] < 0, "Experience"] = 0

In [27]:
bank_loan["Experience"].min()
#That confirms that there are no negative Experience values left.

0

In [28]:
bank_loan.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 14 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   ID                  5000 non-null   int64
 1   Age                 5000 non-null   int64
 2   Experience          5000 non-null   int64
 3   Income              5000 non-null   int64
 4   ZIP Code            5000 non-null   int64
 5   Family              5000 non-null   int64
 6   CCAvg               5000 non-null   object
 7   Education           5000 non-null   int64
 8   Mortgage            5000 non-null   int64
 9   Personal Loan       5000 non-null   int64
 10  Securities Account  5000 non-null   int64
 11  CD Account          5000 non-null   int64
 12  Online              5000 non-null   int64
 13  CreditCard          5000 non-null   int64
dtypes: int64(13), object(1)
memory usage: 547.0+ KB

In [29]:
bank_loan.describe()

,ID,Age,Experience,Income,ZIP Code,Family,Education,Mortgage,Personal Loan,Securities Account,CD Account,Online,CreditCard
count,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.00000,5000.000000,5000.000000
mean,2500.500000,45.338400,20.119600,73.774200,93152.503200,2.396400,1.881000,56.498800,0.096000,0.104400,0.06040,0.596800,0.294000
std,1443.520003,11.463166,11.440484,46.033729,2121.852005,1.147663,0.839869,101.713802,0.294621,0.305809,0.23825,0.490589,0.455637
min,1.000000,23.000000,0.000000,8.000000,9307.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000
25%,1250.750000,35.000000,10.000000,39.000000,91911.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000
50%,2500.500000,45.000000,20.000000,64.000000,93437.000000,2.000000,2.000000,0.000000,0.000000,0.000000,0.00000,1.000000,0.000000
75%,3750.250000,55.000000,30.000000,98.000000,94608.000000,3.000000,3.000000,101.000000,0.000000,0.000000,0.00000,1.000000,1.000000
max,5000.000000,67.000000,43.000000,224.000000,96651.000000,4.000000,3.000000,635.000000,1.000000,1.000000,1.00000,1.000000,1.000000

## Correct CCAvg Values

The `CCAvg` column was stored as an `object` data type and contained values such as `1/60` and `2/70`.

These values were intended to represent decimal numbers, so `/` was replaced with `.`.

In [32]:
bank_loan["CCAvg"].head(20)

0     1/60
1     1/50
2     1/00
3     2/70
4     1/00
5     0/40
6     1/50
7     0/30
8     0/60
9     8/90
10    2/40
11    0/10
12    3/80
13    2/50
14    2/00
15    1/50
16    4/70
17    2/40
18    8/10
19    0/50
Name: CCAvg, dtype: object

In [33]:
bank_loan["CCAvg"] = bank_loan["CCAvg"].str.replace("/", ".", regex=False)

In [34]:
bank_loan["CCAvg"] = pd.to_numeric(bank_loan["CCAvg"])

## Verify the Cleaned Dataset

I checked the dataset again after cleaning to make sure the data types were correct and that no missing or duplicate records were introduced.

In [35]:
bank_loan.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 14 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   ID                  5000 non-null   int64
 1   Age                 5000 non-null   int64
 2   Experience          5000 non-null   int64
 3   Income              5000 non-null   int64
 4   ZIP Code            5000 non-null   int64
 5   Family              5000 non-null   int64
 6   CCAvg               5000 non-null   float64
 7   Education           5000 non-null   int64
 8   Mortgage            5000 non-null   int64
 9   Personal Loan       5000 non-null   int64
 10  Securities Account  5000 non-null   int64
 11  CD Account          5000 non-null   int64
 12  Online              5000 non-null   int64
 13  CreditCard          5000 non-null   int64
dtypes: float64(1), int64(13)
memory usage: 547.0 KB

In [36]:
bank_loan.isnull().sum().sum()

np.int64(0)

In [37]:
bank_loan.duplicated().sum()

np.int64(0)

# Saving the new cleaned Data
using df.to_csv(new_name.csv, index=False)


1.   df → your DataFrame containing the loan data.
2.   .to_csv() → tells Pandas to save the DataFrame as a CSV file.
3.   'bank_loan_cleaned.csv' → the name of the new file.
4.   index=False →don't add row numbers

In [38]:
bank_loan.to_csv('bank_loan_cleaned.csv', index=False)

## Cleaning Summary

The following cleaning steps were completed:

- Checked the dataset structure and contents.
- Checked for missing values; none were found.
- Checked for duplicate rows; none were found.
- Checked categorical and binary columns for unexpected values.
- Corrected negative `Experience` values by replacing them with 0.
- Corrected the formatting of `CCAvg` values by replacing `/` with `.`.
- Converted `CCAvg` from an object type to a numeric type.
- Verified the cleaned dataset.
- Saved the cleaned data as `bank_loan_cleaned.csv`.

The cleaned dataset contains 5,000 records and 14 columns.